---
title: "Nova Report"
subtitle: "Neuzugänge im SLUB-Katalog"
pagetitle: "Nova Report :: SLUB Katalog"
author-meta: "SLUB Dresden"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
lang: "de-DE"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
    mathjax: null
    df_print: paged
    css: ["vendor/slub/webdesign-template/css/font.css", "assets/css/custom.css"]
    includes:
      after_body: assets/html/target.html
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = "..")
```

Zenodo-Community: [SLUB Nova](https://zenodo.org/communities/slub-nova/records) (`slub-nova`)

# Suchserver

## Indexierungen

| Jahr | DOI                                                                | Version |
|:----:|:------------------------------------------------------------------:|:-------:|
| 2024 | [10.5281/zenodo.16881662](https://doi.org/10.5281/zenodo.16881662) | 1.2     |
| 2023 | [10.5281/zenodo.16881739](https://doi.org/10.5281/zenodo.16881739) | 1.2     |
| 2022 | [10.5281/zenodo.16858259](https://doi.org/10.5281/zenodo.16858259) | 1.2     |

```{r indexed-records-input}
indexed_records_series <- readRDS("data/indexed-records-series.RDS")
```

```{r indexed-records-plot}
ggplot2::ggplot(indexed_records_series, ggplot2::aes(x = day, y = count)) +
  ggplot2::geom_col() +
  ggplot2::xlab("Indexierungsdatum") +
  ggplot2::ylab("Anzahl Titel") +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 60, hjust = 1))
```

# Lokalsystem

## Aktivierungen

| Jahr | DOI                                                                | Version |
|:----:|:------------------------------------------------------------------:|:-------:|
| 2024 | [10.5281/zenodo.16385159](https://doi.org/10.5281/zenodo.16385159) | 1.0     |
| 2023 | [10.5281/zenodo.10888494](https://doi.org/10.5281/zenodo.10888494) | 1.0     |
| 2022 | [10.5281/zenodo.10179459](https://doi.org/10.5281/zenodo.10179459) | 1.1     |

```{r newitem-records-input}
newitem_records_series <- readRDS("data/newitem-records-series.RDS")
```

```{r newitem-records-plot}
ggplot2::ggplot(newitem_records_series, ggplot2::aes(x = day, y = count)) +
  ggplot2::geom_col() +
  ggplot2::xlab("Aktivierungsdatum") +
  ggplot2::ylab("Anzahl Titel") +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 60, hjust = 1))
```

## Erwerbungen

| Jahr | DOI                                                                | Version |
|:----:|:------------------------------------------------------------------:|:-------:|
| 2024 | [10.5281/zenodo.16385169](https://doi.org/10.5281/zenodo.16385169) | 1.0     |
| 2023 | [10.5281/zenodo.10888524](https://doi.org/10.5281/zenodo.10888524) | 1.0     |
| 2022 | [10.5281/zenodo.10251277](https://doi.org/10.5281/zenodo.10251277) | 1.1     |

```{r purchase-records-input}
purchase_records_series <- readRDS("data/purchase-records-series.RDS")
```

```{r purchase-records-plot}
ggplot2::ggplot(purchase_records_series, ggplot2::aes(x = day, y = count)) +
  ggplot2::geom_col() +
  ggplot2::xlab("Erwerbungsdatum") +
  ggplot2::ylab("Anzahl Titel") +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 60, hjust = 1))
```
